import { useCallback, useEffect, useRef, useState } from 'react'
import ReactMarkdown from 'react-markdown'
import { useLocation, useNavigate, useParams } from 'react-router-dom'
import { api } from '../api'
import { ArrowLeft, Send } from '../components/icons'
import { useChats } from '../components/Layout'
import { BotAvatar } from '../components/theme'
import Typewriter from '../components/Typewriter'

function ChatImage({ src }) {
  const [state, setState] = useState('loading')
  return (
    <div className="mt-3">
      {state === 'loading' && (
        <div className="grid aspect-square w-64 max-w-full animate-pulse place-items-center rounded-lg bg-ink-800 text-sm text-fog-500">
          Generating image…
        </div>
      )}
      {state === 'error' && <p className="text-sm text-fog-500">The image couldn't be loaded. Try asking again.</p>}
      <a href={src} target="_blank" rel="noreferrer" className={state === 'loaded' ? 'block' : 'hidden'}>
        <img src={src} alt="Generated by the bot" onLoad={() => setState('loaded')} onError={() => setState('error')}
          className="max-h-80 max-w-full rounded-lg" />
      </a>
    </div>
  )
}

function Bubble({ msg, bot, animate, onTick, onDone }) {
  const isUser = msg.role === 'user'
  const [typed, setTyped] = useState(!animate)
  const finish = useCallback(() => {
    setTyped(true)
    onDone?.()
  }, [onDone])

  if (isUser) {
    return (
      <div className="flex animate-rise justify-end">
        <div className="max-w-[80%] whitespace-pre-wrap rounded-2xl rounded-br-sm bg-accent px-4 py-2.5 text-[15px] leading-relaxed text-on-accent">
          {msg.content}
        </div>
      </div>
    )
  }
  return (
    <div className="flex animate-rise gap-3">
      <BotAvatar name={bot.name} avatar={bot.avatar} className="mt-0.5 h-8 w-8 text-base" rounded="rounded-md" />
      <div className="min-w-0 max-w-[80%] rounded-2xl rounded-tl-sm bg-ink-800 px-4 py-2.5 text-[15px] leading-relaxed text-fog-100">
        {animate && !typed ? (
          <Typewriter text={msg.content} onTick={onTick} onDone={finish} />
        ) : (
          <div className="prose-chat"><ReactMarkdown>{msg.content}</ReactMarkdown></div>
        )}
        {msg.image_url && (typed || !animate) && <ChatImage src={msg.image_url} />}
      </div>
    </div>
  )
}

function Thinking({ bot }) {
  return (
    <div className="flex animate-rise gap-3">
      <BotAvatar name={bot.name} avatar={bot.avatar} className="h-8 w-8 text-base" rounded="rounded-md" />
      <div className="flex items-center gap-1 rounded-2xl rounded-tl-sm bg-ink-800 px-4 py-3.5" aria-label="Bot is thinking">
        {[0, 150, 300].map((d) => (
          <span key={d} className="h-1.5 w-1.5 animate-bounce rounded-full bg-fog-500" style={{ animationDelay: `${d}ms` }} />
        ))}
      </div>
    </div>
  )
}

export default function Chat() {
  const { id } = useParams()
  const navigate = useNavigate()
  const location = useLocation()
  // Go back to the previous page; if the chat was opened directly, go to Explore instead.
  const goBack = () => (location.key === 'default' ? navigate('/') : navigate(-1))
  const { refresh } = useChats()
  const [conv, setConv] = useState(null)
  const [messages, setMessages] = useState([])
  const [text, setText] = useState('')
  const [sending, setSending] = useState(false)
  const [typingId, setTypingId] = useState(null) // newest bot reply that is still being "typed"
  const [error, setError] = useState('')
  const scroller = useRef(null)
  const input = useRef(null)

  useEffect(() => {
    setConv(null)
    setError('')
    setTypingId(null)
    api(`/conversations/${id}`)
      .then((c) => {
        setConv(c)
        setMessages(c.messages)
      })
      .catch((e) => setError(e.message))
  }, [id])

  const toBottom = useCallback(() => {
    const el = scroller.current
    if (el) el.scrollTop = el.scrollHeight
  }, [])
  useEffect(toBottom, [messages, sending, toBottom])

  // Grow the message box with its content (up to ~6 lines).
  useEffect(() => {
    const el = input.current
    if (!el) return
    el.style.height = 'auto'
    el.style.height = Math.min(el.scrollHeight, 160) + 'px'
  }, [text])

  const send = async (e) => {
    e?.preventDefault()
    const content = text.trim()
    if (!content || sending) return
    setError('')
    setSending(true)
    setTypingId(null)
    setText('')
    const temp = { id: `tmp-${Date.now()}`, role: 'user', content }
    setMessages((m) => [...m, temp])
    try {
      const res = await api(`/conversations/${id}/messages`, { method: 'POST', body: { content } })
      setMessages((m) => [...m.filter((x) => x.id !== temp.id), res.user_message, res.bot_message])
      setTypingId(res.bot_message.id)
      if (messages.length === 0) refresh() // the chat title is set from the first message
    } catch (err) {
      setMessages((m) => m.filter((x) => x.id !== temp.id))
      setText(content)
      setError(err.message)
    } finally {
      setSending(false)
    }
  }

  const onKeyDown = (e) => {
    if (e.key === 'Enter' && !e.shiftKey) send(e)
  }

  const typingDone = useCallback(() => {
    setTypingId(null)
    setTimeout(toBottom, 50)
  }, [toBottom])

  if (!conv) {
    return <div className="grid h-full place-items-center text-fog-500">{error || 'Loading chat…'}</div>
  }

  const bot = { name: conv.bot_name, avatar: conv.bot_avatar }

  return (
    <div className="flex h-full flex-col">
      <header className="flex items-center gap-3 border-b border-ink-700 bg-ink-950 px-3 py-2.5 md:px-6">
        <button onClick={goBack} className="btn-ghost px-2.5" title="Back" aria-label="Go back">
          <ArrowLeft className="h-5 w-5" />
          <span className="hidden sm:inline">Back</span>
        </button>
        <BotAvatar name={bot.name} avatar={bot.avatar} className="h-9 w-9 text-lg" rounded="rounded-md" />
        <div className="min-w-0">
          <h1 className="truncate font-semibold">{bot.name}</h1>
          <p className="text-xs text-fog-500">Remembers this conversation</p>
        </div>
      </header>

      <div ref={scroller} className="flex-1 overflow-y-auto px-4 py-6">
        <div className="mx-auto max-w-3xl space-y-4">
          {messages.length === 0 && (
            <div className="flex flex-col items-center py-16 text-center">
              <BotAvatar name={bot.name} avatar={bot.avatar} className="h-16 w-16 text-4xl" rounded="rounded-xl" />
              <h2 className="mt-5 font-display text-2xl font-bold tracking-tight">Say hi to {bot.name}</h2>
              <p className="mt-1.5 max-w-sm text-fog-300">You can also ask it to draw something.</p>
            </div>
          )}
          {messages.map((m) => (
            <Bubble key={m.id} msg={m} bot={bot} animate={m.id === typingId} onTick={toBottom} onDone={typingDone} />
          ))}
          {sending && <Thinking bot={bot} />}
        </div>
      </div>

      <form onSubmit={send} className="px-4 pb-4 pt-2">
        {error && <p className="mx-auto mb-2 max-w-3xl rounded-lg bg-coral/10 px-3 py-2 text-sm text-coral">{error}</p>}
        <div className="mx-auto flex max-w-3xl items-end gap-2 rounded-xl border border-ink-700 bg-ink-900 p-1.5 transition-colors focus-within:border-ink-600">
          <textarea ref={input} className="max-h-40 min-h-[40px] flex-1 resize-none bg-transparent px-2.5 py-2 text-[15px] text-fog-100 outline-none placeholder:text-fog-500"
            rows={1} value={text} onChange={(e) => setText(e.target.value)} onKeyDown={onKeyDown}
            placeholder={`Message ${bot.name}…`} maxLength={4000} autoFocus aria-label="Message" />
          <button className="btn-primary h-10 w-10 shrink-0 p-0" disabled={!text.trim() || sending} aria-label="Send message">
            <Send className="h-[18px] w-[18px]" />
          </button>
        </div>
              </form>
    </div>
  )
}
